-- Discovery comes home (ADR 0041, back-office slice 2): `audits` becomes a
-- row of the OPERATOR tenant, attached to the party it is about, and scoped
-- like every tenant table — superadmin_all + member_all — instead of
-- superadmin-only.
--
-- ONE MIGRATION, ON PURPOSE. Until now `tenant_id` meant the tenant the audit
-- was ABOUT, and the only policy was superadmin-only. Adding the member policy
-- before moving the rows would let a client's staff read a discovery
-- transcript about themselves; moving the rows before the policy would hide
-- them from the operator. So the rows move and the policy lands together, and
-- the whole thing REFUSES to run where it would leave a transcript under its
-- old tenant: a database that has audits but no named operator.
--
-- `party_id` comes from the workspace's `operator_party_id` where slice 1 has
-- already made a party; otherwise it stays null and `origin_tenant_id`
-- remembers the tenant, so `ensureOperatorParty` can attach the record the
-- day that business gets its party. Generated by drizzle-kit for the columns
-- and the index; the guard, the moves and the policy are written by hand.

ALTER TABLE "audits" ADD COLUMN "party_id" uuid;--> statement-breakpoint
ALTER TABLE "audits" ADD COLUMN "origin_tenant_id" uuid;--> statement-breakpoint
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM audits)
     AND NOT EXISTS (SELECT 1 FROM tenants WHERE is_operator) THEN
    RAISE EXCEPTION 'audits exist but no operator tenant is named: run scripts/operator-tenant.ts first (docs/modules/back-office.md, slice 2)';
  END IF;
END $$;--> statement-breakpoint
UPDATE audits a
   SET origin_tenant_id = a.tenant_id,
       party_id = t.operator_party_id,
       tenant_id = (SELECT id FROM tenants WHERE is_operator)
  FROM tenants t
 WHERE t.id = a.tenant_id
   AND NOT t.is_operator;--> statement-breakpoint
UPDATE audits
   SET tenant_id = (SELECT id FROM tenants WHERE is_operator)
 WHERE tenant_id IS NULL;--> statement-breakpoint
ALTER TABLE "audits" ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
CREATE INDEX "audits_tenant_party_idx" ON "audits" USING btree ("tenant_id","party_id");--> statement-breakpoint
CREATE POLICY audits_member_all ON "audits"
  USING ("tenant_id" = app_current_tenant())
  WITH CHECK ("tenant_id" = app_current_tenant());
