import {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Banknote,
  Bell,
  Bookmark,
  Building2,
  CalendarClock,
  CalendarDays,
  Camera,
  Check,
  ChevronDown,
  ChevronUp,
  Trophy,
  TriangleAlert,
  Ban,
  Receipt,
  SkipForward,
  CloudOff,
  ChevronLeft,
  ChevronRight,
  CircleQuestionMark,
  BookOpen,
  ClipboardPaste,
  Copy,
  Crosshair,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileDown,
  FileText,
  FileUp,
  Filter,
  Flag,
  PiggyBank,
  Play,
  FolderInput,
  FolderOpen,
  FolderPlus,
  Globe,
  GripVertical,
  History,
  Image as ImageIcon,
  ImagePlus,
  ImageUp,
  Images,
  Inbox,
  LayoutGrid,
  Link as LinkIcon,
  Link2,
  List,
  Package,
  Lock,
  LockOpen,
  Mail,
  Menu,
  Monitor,
  MoreHorizontal,
  Paperclip,
  Megaphone,
  MegaphoneOff,
  Minus,
  ChefHat,
  Timer,
  BellRing,
  ChartColumn,
  ListPlus,
  Moon,
  Settings2,
  Snowflake,
  Pause,
  Pencil,
  PenLine,
  Plus,
  Printer,
  RefreshCw,
  RotateCcw,
  Save,
  ScanLine,
  Search,
  MessageSquarePlus,
  Mic,
  MicOff,
  Send,
  Share2,
  Smartphone,
  Sparkles,
  SquarePen,
  Star,
  Table2,
  Tablet,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Undo2,
  Unlink,
  Upload,
  Volume2,
  VolumeX,
  UserRound,
  Wallet,
  X,
  type LucideIcon,
} from "lucide-react";
import { ICONS } from "./icon-registry";

/**
 * The icons a guide may draw on a control — `{button:New bill|primary|plus}`,
 * `{icon:circle-question-mark}` — by the name an author would guess.
 *
 * A separate map from `ICONS` because that one is the module registry, where a
 * missing key is a wrong sidebar; this one is decoration on a facsimile. The
 * registry's names are accepted too, so a guide can draw a tool's own icon
 * when it tells the reader which sidebar row to look for. No fallback: an
 * unknown name draws nothing at render time and fails `tests/guides.test.ts`,
 * which is how a typo is caught before a client reads it.
 */
export const CONTROL_ICONS: Record<string, LucideIcon> = {
  archive: Archive,
  "archive-restore": ArchiveRestore,
  // A sentence waiting for signal (tell.md, slice D2).
  "cloud-off": CloudOff,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  // Workouts' "Move on to Phase 2" (fitness.md, F3).
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  banknote: Banknote,
  // Workouts' reminders on the program page (fitness.md, F4a).
  bell: Bell,
  bookmark: Bookmark,
  building: Building2,
  // Putting a social post on the calendar (marketing, slice S1).
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  camera: Camera,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "player-skip-forward": SkipForward,
  "receipt": Receipt,
  "ban": Ban,
  "trophy": Trophy,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-question-mark": CircleQuestionMark,
  // Opening the proposal as a brochure (jobs, E5a).
  "book-open": BookOpen,
  // Pasting a block of estimate lines (jobs, E3a).
  "clipboard-paste": ClipboardPaste,
  copy: Copy,
  // Re-centring a post's crop (marketing, slice S1).
  crosshair: Crosshair,
  download: Download,
  "external-link": ExternalLink,
  eye: Eye,
  // The posture check's camera, shown and hidden again (posture.md, slice 1).
  "eye-off": EyeOff,
  "file-down": FileDown,
  "file-text": FileText,
  "file-up": FileUp,
  filter: Filter,
  // What a posture check marks in a workout program (posture.md, slice 3c).
  flag: Flag,
  "piggy-bank": PiggyBank,
  globe: Globe,
  "grip-vertical": GripVertical,
  "folder-input": FolderInput,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  history: History,
  image: ImageIcon,
  "image-plus": ImagePlus,
  "image-up": ImageUp,
  images: Images,
  inbox: Inbox,
  "layout-grid": LayoutGrid,
  link: LinkIcon,
  "link-2": Link2,
  list: List,
  package: Package,
  lock: Lock,
  "lock-open": LockOpen,
  mail: Mail,
  menu: Menu,
  monitor: Monitor,
  "more-horizontal": MoreHorizontal,
  paperclip: Paperclip,
  // Pausing and resuming a social account (marketing, slice S0).
  pause: Pause,
  play: Play,
  pencil: Pencil,
  "pen-line": PenLine,
  "pen-square": SquarePen,
  plus: Plus,
  printer: Printer,
  refresh: RefreshCw,
  "rotate-ccw": RotateCcw,
  save: Save,
  // The Posture check card on the Workouts page (posture.md, slice 1).
  "scan-line": ScanLine,
  search: Search,
  send: Send,
  // The advisor's New thread (livestock, slice 11).
  "message-square-plus": MessageSquarePlus,
  // A recipe's servings, one fewer (food.md, D1); `plus` is its twin.
  minus: Minus,
  // Cook mode (food.md, D1b): the Cook button, a time in a step, a timer ringing.
  "chef-hat": ChefHat,
  timer: Timer,
  "bell-ring": BellRing,
  // Health's Today and Progress (health.md, H1): the cards' headings, the
  // Progress button, the habits' Change and Add, and which way a week went.
  "chart-column": ChartColumn,
  "list-plus": ListPlus,
  moon: Moon,
  "settings-2": Settings2,
  snowflake: Snowflake,
  // "Say it" on the tell box (voice slice 2, ADR 0049); cook mode's
  // Hands-free switch, on and off (food.md, D1c).
  mic: Mic,
  "mic-off": MicOff,
  share: Share2,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  table: Table2,
  tablet: Tablet,
  tag: Tag,
  // Food's Set targets and Change targets on Today (food.md, D4a).
  target: Target,
  trash: Trash2,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  undo: Undo2,
  unlink: Unlink,
  upload: Upload,
  "user-round": UserRound,
  // The tell box says its answer back when it was spoken to, and this pair is
  // the switch that turns that off (tell.md, slice D1).
  "volume-2": Volume2,
  "volume-x": VolumeX,
  // Workout mode's coach's voice, on and off; the pair above is its sounds
  // (fitness.md, F2b).
  megaphone: Megaphone,
  "megaphone-off": MegaphoneOff,
  // A personal register's card (ADR 0034) wears this instead of the bank mark.
  wallet: Wallet,
  x: X,
  // A warning drawn beside its words: Workouts' effort warning and a phase not
  // yet open (fitness.md, F3).
  "triangle-alert": TriangleAlert,
};

export function getControlIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return CONTROL_ICONS[name] ?? ICONS[name] ?? null;
}

/** Every name a marker may use, for the test that checks the real tree. */
export function controlIconNames(): Set<string> {
  return new Set([...Object.keys(CONTROL_ICONS), ...Object.keys(ICONS)]);
}
