import {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Banknote,
  Bookmark,
  Building2,
  CalendarDays,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleQuestionMark,
  Copy,
  Download,
  ExternalLink,
  Eye,
  FileDown,
  FileText,
  FileUp,
  Filter,
  FolderInput,
  FolderOpen,
  FolderPlus,
  Globe,
  GripVertical,
  History,
  Image as ImageIcon,
  ImagePlus,
  ImageUp,
  Inbox,
  LayoutGrid,
  Link as LinkIcon,
  Link2,
  List,
  Lock,
  LockOpen,
  Mail,
  Menu,
  MoreHorizontal,
  Paperclip,
  Pencil,
  PenLine,
  Plus,
  Printer,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Send,
  Share2,
  Sparkles,
  SquarePen,
  Star,
  Table2,
  Tag,
  Trash2,
  Undo2,
  Unlink,
  Upload,
  UserRound,
  X,
  type LucideIcon,
} from "lucide-react";
import { ICONS } from "./icon-registry";

/**
 * The icons a guide may draw on a control — `{button:New bill|primary|plus}`,
 * `{icon:circle-question-mark}` — by the name an author would guess.
 *
 * A separate map from `ICONS` because that one is the module registry, where a
 * missing key is a wrong sidebar; this one is decoration on a facsimile. The
 * registry's names are accepted too, so a guide can draw a tool's own icon
 * when it tells the reader which sidebar row to look for. No fallback: an
 * unknown name draws nothing at render time and fails `tests/guides.test.ts`,
 * which is how a typo is caught before a client reads it.
 */
export const CONTROL_ICONS: Record<string, LucideIcon> = {
  archive: Archive,
  "archive-restore": ArchiveRestore,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  banknote: Banknote,
  bookmark: Bookmark,
  building: Building2,
  "calendar-days": CalendarDays,
  camera: Camera,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-question-mark": CircleQuestionMark,
  copy: Copy,
  download: Download,
  "external-link": ExternalLink,
  eye: Eye,
  "file-down": FileDown,
  "file-text": FileText,
  "file-up": FileUp,
  filter: Filter,
  globe: Globe,
  "grip-vertical": GripVertical,
  "folder-input": FolderInput,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  history: History,
  image: ImageIcon,
  "image-plus": ImagePlus,
  "image-up": ImageUp,
  inbox: Inbox,
  "layout-grid": LayoutGrid,
  link: LinkIcon,
  "link-2": Link2,
  list: List,
  lock: Lock,
  "lock-open": LockOpen,
  mail: Mail,
  menu: Menu,
  "more-horizontal": MoreHorizontal,
  paperclip: Paperclip,
  pencil: Pencil,
  "pen-line": PenLine,
  "pen-square": SquarePen,
  plus: Plus,
  printer: Printer,
  refresh: RefreshCw,
  "rotate-ccw": RotateCcw,
  save: Save,
  search: Search,
  send: Send,
  share: Share2,
  sparkles: Sparkles,
  star: Star,
  table: Table2,
  tag: Tag,
  trash: Trash2,
  undo: Undo2,
  unlink: Unlink,
  upload: Upload,
  "user-round": UserRound,
  x: X,
};

export function getControlIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return CONTROL_ICONS[name] ?? ICONS[name] ?? null;
}

/** Every name a marker may use, for the test that checks the real tree. */
export function controlIconNames(): Set<string> {
  return new Set([...Object.keys(CONTROL_ICONS), ...Object.keys(ICONS)]);
}
