/**
 * Provisioning the `app_user` role, in ONE place.
 *
 * There are now two callers and they must not drift: `create-app-role.ts`
 * (interactive, rewrites `.env`, used against Neon) and `ci-provision-db.ts`
 * (non-interactive, used against the Postgres container inside a CI runner).
 * A second hand-maintained copy of these grants is exactly the thing that ends
 * up subtly different, and the failure mode is the worst one available: an
 * isolation suite that passes while certifying nothing.
 *
 * THE INVARIANT THIS EXISTS TO PROTECT: `app_user` must never have BYPASSRLS.
 * Neon's owner role does, which is why the app connects as this role instead —
 * and a Neon-MINTED role would also get `neon_superuser` and bypass RLS, which
 * is why it is created in SQL rather than through any provider's API. The check
 * at the end is not a formality; it is the whole point.
 */

/** Anything that can run a SQL string. Keeps this file driver-agnostic. */
export type Query = (sql: string) => Promise<{ rows: unknown[] }>;

export async function provisionAppUser(
  query: Query,
  password: string,
): Promise<void> {
  const existing = await query(
    "select 1 from pg_roles where rolname = 'app_user'",
  );
  // The identifier is fixed and the password is generated by the caller —
  // nothing user-controlled is interpolated here.
  if (existing.rows.length > 0) {
    await query(`ALTER ROLE app_user WITH LOGIN PASSWORD '${password}'`);
  } else {
    await query(
      `CREATE ROLE app_user WITH LOGIN PASSWORD '${password}' NOCREATEDB NOCREATEROLE`,
    );
  }

  await query(`GRANT USAGE ON SCHEMA public TO app_user`);
  await query(
    `GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user`,
  );
  await query(`GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user`);
  // Future tables too, so a new migration does not silently create a table the
  // app cannot read.
  await query(
    `ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user`,
  );
  await query(
    `ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app_user`,
  );
}

/**
 * Refuse to continue if `app_user` can bypass RLS.
 *
 * Called by both provisioning paths. If this ever throws, every tenant policy
 * in the database has stopped applying and the isolation suite would report a
 * green tick over nothing.
 */
export async function assertNoBypassRls(query: Query): Promise<void> {
  const result = await query(
    `select rolbypassrls from pg_roles where rolname = 'app_user'`,
  );
  const row = result.rows[0] as { rolbypassrls?: boolean } | undefined;
  if (row?.rolbypassrls) {
    throw new Error(
      "app_user has BYPASSRLS. Every tenant policy would stop applying and " +
        "the isolation suite would certify nothing. Refusing to continue.",
    );
  }
}
