/**
 * The emoji the picker offers.
 *
 * WHY THIS IS A HAND-WRITTEN TABLE RATHER THAN A DEPENDENCY. The full Unicode
 * emoji set is ~1,900 characters and the libraries that ship it carry a
 * megabyte of data plus a picker component with its own opinions. This is a
 * business mail composer: the useful set is the couple of hundred that appear in
 * work correspondence, and shipping the other seventeen hundred costs every
 * reader of every page a download for skin-tone variants of a mermaid.
 *
 * WHY IT NEEDS NO SANITIZER RULE AT ALL, which is the reason emoji were the
 * cheapest thing on the list: **an emoji is a text character, not an image.**
 * It is inserted with `insertText`, travels in the HTML part as a UTF-8
 * character, and survives into the plain-text alternative for free. Nothing in
 * `compose/html.ts` had to change. The `<img>`-based emoji some clients use
 * would have needed the opposite of everything that file is built around.
 *
 * Pure, free of `server-only`.
 */

export interface EmojiGroup {
  id: string;
  label: string;
  /** Shown on the category tab. Itself an emoji, so no icon import. */
  icon: string;
  emoji: readonly EmojiEntry[];
}

/** `[character, search terms]`. The terms are lowercase and space-separated. */
export type EmojiEntry = readonly [string, string];

export const EMOJI_GROUPS: readonly EmojiGroup[] = [
  {
    id: "smileys",
    label: "Smileys",
    icon: "🙂",
    emoji: [
      ["😀", "grin smile happy"],
      ["😃", "smile happy joy"],
      ["😄", "smile happy laugh"],
      ["😁", "beam grin happy"],
      ["😆", "laugh squint happy"],
      ["😅", "sweat laugh relief"],
      ["🤣", "rofl laugh floor"],
      ["😂", "joy tears laugh cry"],
      ["🙂", "slight smile"],
      ["🙃", "upside down silly"],
      ["😉", "wink"],
      ["😊", "blush smile happy"],
      ["😇", "halo angel innocent"],
      ["😍", "heart eyes love"],
      ["😘", "kiss blow love"],
      ["😗", "kiss"],
      ["😋", "yum tongue tasty"],
      ["😛", "tongue cheeky"],
      ["🤪", "zany silly crazy"],
      ["🤨", "raised eyebrow sceptical"],
      ["🧐", "monocle inspect"],
      ["🤓", "nerd glasses"],
      ["😎", "cool sunglasses"],
      ["🥳", "party celebrate"],
      ["😏", "smirk"],
      ["😒", "unamused meh"],
      ["😞", "disappointed sad"],
      ["😔", "pensive sad"],
      ["😟", "worried"],
      ["🙁", "frown slight sad"],
      ["😣", "persevere struggle"],
      ["😖", "confounded"],
      ["😫", "tired"],
      ["😩", "weary"],
      ["🥺", "pleading please beg"],
      ["😢", "cry sad tear"],
      ["😭", "sob cry loud"],
      ["😤", "triumph steam annoyed"],
      ["😠", "angry"],
      ["😡", "rage furious angry"],
      ["🤯", "mind blown shocked"],
      ["😳", "flushed embarrassed"],
      ["🥵", "hot heat"],
      ["🥶", "cold freezing"],
      ["😱", "scream fear shock"],
      ["😨", "fearful"],
      ["😰", "anxious sweat"],
      ["😥", "sad relieved"],
      ["🤗", "hug"],
      ["🤔", "thinking think hmm"],
      ["🤭", "oops giggle"],
      ["🤫", "shush quiet secret"],
      ["🤥", "lying liar"],
      ["😶", "no mouth speechless"],
      ["😐", "neutral"],
      ["😑", "expressionless"],
      ["😬", "grimace awkward"],
      ["🙄", "eye roll"],
      ["😴", "sleep zzz"],
      ["🤤", "drool"],
      ["😪", "sleepy"],
      ["😵", "dizzy"],
      ["🤐", "zipper mouth quiet"],
      ["🥴", "woozy"],
      ["🤢", "nauseated sick"],
      ["🤮", "vomit sick"],
      ["🤧", "sneeze ill"],
      ["😷", "mask ill"],
      ["🤒", "thermometer ill sick"],
      ["🤕", "bandage hurt injured"],
      ["🥱", "yawn tired bored"],
    ],
  },
  {
    id: "people",
    label: "People",
    icon: "👍",
    emoji: [
      ["👍", "thumbs up yes good approve ok"],
      ["👎", "thumbs down no bad"],
      ["👌", "ok perfect"],
      ["🤝", "handshake deal agree"],
      ["👏", "clap applause well done"],
      ["🙌", "raise hands celebrate praise"],
      ["🙏", "pray thanks please"],
      ["✌️", "peace victory"],
      ["🤞", "fingers crossed luck hope"],
      ["👋", "wave hello hi bye"],
      ["🤙", "call me shaka"],
      ["💪", "muscle strong"],
      ["✍️", "writing sign"],
      ["👀", "eyes look watch"],
      ["🫡", "salute yes sir"],
      ["🤦", "facepalm"],
      ["🤷", "shrug dunno"],
      ["👉", "point right"],
      ["👈", "point left"],
      ["👆", "point up above"],
      ["👇", "point down below"],
      ["☝️", "point up one"],
      ["🖐️", "hand stop five"],
      ["🫱", "handshake right"],
      ["💁", "information desk tipping hand"],
      ["🙋", "raising hand question volunteer"],
      ["🧑‍💻", "developer coder laptop"],
      ["👷", "construction worker builder"],
      ["🧑‍🔧", "mechanic engineer"],
      ["🧑‍🌾", "farmer"],
      ["🧑‍🍳", "chef cook"],
      ["🧑‍⚕️", "doctor nurse health"],
      ["🕵️", "detective investigate"],
      ["👶", "baby"],
      ["🧑", "person adult"],
      ["👨", "man"],
      ["👩", "woman"],
    ],
  },
  {
    id: "nature",
    label: "Nature",
    icon: "🌿",
    emoji: [
      ["🌞", "sun sunny bright"],
      ["🌤️", "sun cloud"],
      ["⛅", "cloud sun partly"],
      ["☁️", "cloud overcast"],
      ["🌧️", "rain wet"],
      ["⛈️", "storm thunder rain"],
      ["🌩️", "lightning thunder"],
      ["❄️", "snow snowflake cold"],
      ["☃️", "snowman winter"],
      ["🌪️", "tornado"],
      ["🌈", "rainbow"],
      ["🔥", "fire hot flame"],
      ["💧", "water drop"],
      ["🌊", "wave sea ocean water"],
      ["🌱", "seedling grow plant"],
      ["🌿", "herb plant leaf"],
      ["🍀", "clover luck"],
      ["🌳", "tree"],
      ["🌲", "evergreen tree pine"],
      ["🌵", "cactus"],
      ["🌷", "tulip flower"],
      ["🌸", "blossom flower"],
      ["🌻", "sunflower"],
      ["🌹", "rose flower"],
      ["🐝", "bee"],
      ["🐛", "bug caterpillar"],
      ["🐕", "dog"],
      ["🐈", "cat"],
      ["🐴", "horse"],
      ["🐄", "cow cattle"],
      ["🐑", "sheep"],
      ["🐦", "bird"],
      ["🐟", "fish"],
      ["🦅", "eagle bird"],
      ["🐭", "mouse"],
      ["🕷️", "spider"],
      ["🐀", "rat rodent pest"],
    ],
  },
  {
    id: "food",
    label: "Food",
    icon: "☕",
    emoji: [
      ["☕", "coffee tea hot drink"],
      ["🍵", "tea green"],
      ["🥤", "drink cup soda"],
      ["🍺", "beer pint"],
      ["🍻", "cheers beers"],
      ["🥂", "cheers champagne toast"],
      ["🍷", "wine"],
      ["🥃", "whisky whiskey"],
      ["🍽️", "plate cutlery meal dinner"],
      ["🍕", "pizza"],
      ["🍔", "burger"],
      ["🌭", "hot dog"],
      ["🥪", "sandwich"],
      ["🌮", "taco"],
      ["🍟", "fries chips"],
      ["🍞", "bread"],
      ["🧀", "cheese"],
      ["🥚", "egg"],
      ["🥓", "bacon"],
      ["🍎", "apple fruit"],
      ["🍌", "banana fruit"],
      ["🍓", "strawberry fruit"],
      ["🍇", "grapes fruit"],
      ["🥕", "carrot vegetable"],
      ["🥗", "salad"],
      ["🎂", "cake birthday"],
      ["🍰", "cake slice"],
      ["🍪", "cookie biscuit"],
      ["🍫", "chocolate"],
      ["🍿", "popcorn"],
    ],
  },
  {
    id: "travel",
    label: "Travel",
    icon: "🚚",
    emoji: [
      ["🚗", "car drive"],
      ["🚕", "taxi cab"],
      ["🚐", "van minibus"],
      ["🚚", "truck lorry delivery"],
      ["🚛", "lorry articulated truck"],
      ["🚜", "tractor farm"],
      ["🏗️", "construction crane site"],
      ["🚧", "roadworks barrier construction"],
      ["🛻", "pickup truck ute"],
      ["🚲", "bicycle bike"],
      ["🏍️", "motorbike motorcycle"],
      ["✈️", "plane flight travel"],
      ["🚁", "helicopter"],
      ["🚢", "ship boat"],
      ["⛵", "sailboat yacht"],
      ["🚂", "train rail"],
      ["🚌", "bus"],
      ["🏠", "house home"],
      ["🏡", "house garden home"],
      ["🏢", "office building"],
      ["🏭", "factory plant"],
      ["🏬", "shop store department"],
      ["🏥", "hospital"],
      ["🏫", "school"],
      ["🗺️", "map"],
      ["📍", "pin location place"],
      ["🧭", "compass direction"],
      ["🚀", "rocket launch"],
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: "📎",
    emoji: [
      ["📎", "paperclip attach"],
      ["📌", "pin"],
      ["📁", "folder file"],
      ["📂", "folder open"],
      ["📄", "document page file"],
      ["📃", "page curl document"],
      ["📋", "clipboard list"],
      ["📊", "chart bar graph data"],
      ["📈", "chart up growth increase"],
      ["📉", "chart down decrease loss"],
      ["🗓️", "calendar date schedule"],
      ["⏰", "alarm clock time"],
      ["⏳", "hourglass waiting time"],
      ["💰", "money bag cash"],
      ["💵", "money dollar cash note"],
      ["💳", "card credit payment"],
      ["🧾", "receipt invoice bill"],
      ["🏦", "bank"],
      ["✉️", "envelope email mail"],
      ["📧", "email mail"],
      ["📨", "incoming mail"],
      ["📮", "postbox mail"],
      ["📞", "phone call telephone"],
      ["📱", "mobile phone smartphone"],
      ["💻", "laptop computer"],
      ["🖥️", "desktop computer monitor"],
      ["🖨️", "printer print"],
      ["⌨️", "keyboard"],
      ["🔑", "key"],
      ["🔒", "lock secure locked"],
      ["🔓", "unlock open"],
      ["🔧", "spanner wrench tool fix"],
      ["🔨", "hammer tool"],
      ["🪛", "screwdriver tool"],
      ["🪚", "saw tool"],
      ["🧰", "toolbox tools"],
      ["⚙️", "gear settings cog"],
      ["🔌", "plug power electric"],
      ["💡", "bulb idea light"],
      ["🔋", "battery power"],
      ["🧱", "brick wall"],
      ["📦", "package box parcel"],
      ["🗑️", "bin trash delete rubbish"],
      ["📷", "camera photo"],
      ["🎥", "video camera film"],
      ["🔍", "search magnify find"],
      ["📏", "ruler measure"],
      ["📐", "set square measure angle"],
      ["✏️", "pencil write"],
      ["🖊️", "pen write"],
      ["📝", "memo note write"],
      ["🏷️", "label tag"],
      ["🛡️", "shield protect security"],
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "✅",
    emoji: [
      ["✅", "check tick done yes complete"],
      ["☑️", "checkbox ticked done"],
      ["✔️", "check tick done"],
      ["❌", "cross no wrong cancel"],
      ["❎", "cross no"],
      ["⚠️", "warning caution alert"],
      ["🚨", "alert siren emergency urgent"],
      ["‼️", "urgent exclamation important"],
      ["❗", "exclamation important"],
      ["❓", "question"],
      ["⭐", "star favourite"],
      ["🌟", "star glowing"],
      ["💯", "hundred perfect score"],
      ["🔔", "bell notify reminder"],
      ["🔕", "bell off mute"],
      ["♻️", "recycle"],
      ["🆕", "new"],
      ["🆗", "ok"],
      ["🔴", "red circle"],
      ["🟠", "orange circle"],
      ["🟡", "yellow circle"],
      ["🟢", "green circle go"],
      ["🔵", "blue circle"],
      ["⚫", "black circle"],
      ["⬜", "white square"],
      ["➡️", "arrow right next"],
      ["⬅️", "arrow left back"],
      ["⬆️", "arrow up"],
      ["⬇️", "arrow down"],
      ["🔄", "refresh repeat sync"],
      ["➕", "plus add"],
      ["➖", "minus subtract"],
      ["©️", "copyright"],
      ["®️", "registered"],
      ["™️", "trademark"],
      ["❤️", "heart love red"],
      ["💚", "green heart"],
      ["💙", "blue heart"],
      ["🎉", "party tada celebrate congrats"],
      ["🎊", "confetti celebrate"],
      ["🏆", "trophy win award"],
      ["🥇", "gold medal first"],
      ["🎯", "target bullseye goal"],
      ["💤", "sleep zzz"],
    ],
  },
] as const;

/**
 * Search the table.
 *
 * Matches the character itself as well as its terms, so pasting an emoji into
 * the box finds it — which is how somebody asks "what is this one called".
 * An empty query returns nothing rather than everything: the caller shows its
 * groups in that case, and returning 300 results for no input would replace a
 * browsable picker with a wall.
 */
export function searchEmoji(query: string, limit = 60): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (q.length === 0) return [];
  const all = EMOJI_GROUPS.flatMap((g) => g.emoji);

  // Terms that START with the query rank above ones that merely contain it, so
  // "car" offers 🚗 before 🃏-adjacent matches like "card".
  const starts: EmojiEntry[] = [];
  const contains: EmojiEntry[] = [];
  for (const entry of all) {
    if (entry[0] === q) {
      starts.push(entry);
      continue;
    }
    const terms = entry[1].split(" ");
    if (terms.some((t) => t.startsWith(q))) starts.push(entry);
    else if (entry[1].includes(q)) contains.push(entry);
  }
  return [...starts, ...contains].slice(0, limit);
}
